name: run-tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: 
      image: silkeh/clang:18
      options: --user root
    steps:
      - name: Install deps
        run: apt update && apt install -y git ninja-build valgrind libgflags-dev
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build --target lin_check_test
      - name: Run lin check test
        run: ./build/test/runtime/lin_check_test
  verifying-test-lock-free-queue:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: 
      image: silkeh/clang:18
      options: --user root
    steps:
      - name: Install deps
        run: |
          apt update && apt install -y git ninja-build valgrind libgoogle-glog-dev libsnappy-dev protobuf-compiler
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build --target verifying/targets/nonlinear_queue
      - name: Run nonlinear_queue with pct strategy
        run: |
          ./build/verifying/targets/nonlinear_queue --strategy pct --tasks 10 --rounds 240
      - name: Run nonlinear_queue with random strategy
        run: |
          ./build/verifying/targets/nonlinear_queue --tasks 4 --rounds 100000 --strategy random --switches 1 || error_code=$?
          if [ "${error_code}" -ne 1 ]; then 
            exit 1
          fi